config/routes.rb
Rails.application.routes.draw do

  # セッションがない時
  root 'homes#new'
  get 'home/about' => 'homes#about'
  # root 'users#show'これはいらない
  # '/' 'home/about' のページは、1.ルートパスを記述してつくる, 2.homeコントローラを新たに作る
  devise_for :users

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resource :book_comments, only: [:create, :destroy]
  end
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
  	favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 199}

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # def email_required?
  # 	false
  # end

  # def email_changed?
  # 	false
  # end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships

  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end


  validates :name, presence: true, length: {minimum: 2, maximum: 20}
  validates :email, presence: true, uniqueness: true
  validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

 before_action :configure_permitted_parameters, if: :devise_controller?

 Refile.secret_key = '6b7e2a7c798502136cf5adc8ee33fabac97fc324e009ab638bd3433ca0b98aeffb70ad28977de42e9fe3cd73ac78941b41519ee7995d70692f23204f7f216ad1'

 def after_sign_in_path_for(resource)
    user_path(resource.id)
 end
 # resource がないと何がログインしたかの情報を持ってこれないため、この引数を消すとエラーが出てしまう

 protected
 def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])
    # はじめに、keys: の中身に':email'を追加していなかったので、emailがnilでかぶっていて登録できなかった可能性がある。
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :password])
 end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
  	book = Book.find(params[:book_id])
  	comment = current_user.book_comments.new(book_comment_params)
  	comment.book_id = book.id
  	comment.save
  	redirect_back(fallback_location: books_url)
  end

  def destroy
  	# bookの情報を取得
  	book = Book.find(params[:book_id])
  	# その投稿内の削除対象のコメントを探して取得
  	comment = current_user.book_comments.find_by(book_id: book.id)
  	# comment.user_id = current_user.id
  	# comment.book_id = book.id
  	comment.destroy
  	redirect_back(fallback_location: books_url)
  end

private
def book_comment_params
  params.require(:book_comment).permit(:comment, :book_id, :user_id)
end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @book = Book.new
    @user = current_user
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def show
    @book = Book.new
    #新規投稿をする
    @book2 = Book.find(params[:id])
    #自分の投稿の一覧表示をする
    @user = User.find(@book2.user_id)
    #@book2のユーザーの情報を表示する,@book2.idだと本のidをとってきてしまう
    @book_comment = BookComment.new
  end

  def create
  	@book = Book.new(book_params)
    # 投稿データを保存するには、Strong Parameters も必要
    @book.user_id = current_user.id
  	if @book.save
  	 redirect_to book_path(@book.id), notice: "You have creatad book successfully."
    else
     @user = current_user
     @books = Book.all
     render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    if @user != current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
     redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
     render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
   params.require(:book).permit(:title, :body, :user_id)
  end
  # form_forを使うときは、Strong Parametersの定義が必要
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
	  book = Book.find(params[:book_id])
      favorite = current_user.favorites.new(book_id: book.id)
      favorite.save
      redirect_back(fallback_location: books_url)
    end

    def destroy
      book = Book.find(params[:book_id])
      favorite = current_user.favorites.find_by(book_id: book.id)
      favorite.destroy
      redirect_back(fallback_location: books_url)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def about
  end

  def new
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @user = User.find(params[:relationship][:following_id])
    current_user.follow!(@user)
    redirect_back(fallback_location: users_url)
  end

  def destroy
    @user = Relationship.find(params[:id]).following
    current_user.unfollow!(@user)
    redirect_back(fallback_location: users_url)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
  	@user = User.find(params[:id])
    #特定のユーザーの情報を表示する
  	@book = Book.new
    #新規投稿をする
  	@books = Book.where(user_id: params[:id])
    #投稿の一覧表示をする, find はとってくるデータが1つだけの時に使う
  end

  def index
    @book = Book.new
    @user = current_user
    # @user = User.find(params[:id])
  	@users = User.all
  end

  def edit
  	@user = User.find(params[:id])
    if @user != current_user
       #redirect_to edit_user_path(@user)：これがあると無限にeditアクションを繰り返してしまう
       redirect_to user_path(current_user)
       # @book = Book.new
       # @books = Book.where(user_id: params[:id])
       # render :show
       #showページの結果として返しているだけなので、URLは変わらない
    end
  end

  def update
  	@user = User.find(params[:id])
    # userデータを保存するには、Strong Parameters も必要
    @user = current_user
  	if @user.update(user_params)
  	 redirect_to user_path(@user), notice: "You have updated user successfully."
    else
     render :edit
     # redirect_toにすると、エラーメッセージが表示されない！！
    end
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/books/_book.html.erb
<!-- 新規投稿 -->
<h2>New book</h2>
 <%= form_for(book) do |f| %>
  <div class="field row">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class:"col-xs-12 book_title" %>
  </div>
  <div class="field row">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class:"col-xs-12 book_body" %>
  </div>
  <div class="actions row">
    <%= f.submit 'Create Book', class:"btn btn-primary col-xs-12" %>
  </div>
 <% end %>

app/views/books/_user.html.erb
<!-- ユーザー情報　-->
 <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 60, 60, class:"attachment user profile_image", fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
        <tr>
        </tr>
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>
    </tbody>
  </table>

<div class="row">
<% if user == current_user %>
  <p><%= link_to "", edit_user_path(user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
<% else %>
  <p><%= link_to "", user_path(current_user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
<% end %>
</div>

app/views/books/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Editing Book</h1>

    <%= form_for(@book) do |f| %>

       <% if @book.errors.any? %>
        <%= @book.errors.count %>errors prohibited this user from being saved:
          <div id="error_explanation" class="alert alert-danger">
            <ul>
              <% @book.errors.full_messages.each do |message| %>
               <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

      <div class="field row">
        <label for="book_title">Title</label>
          <%= f.text_field :title, class:"col-xs-12" %>
      </div>
      <div class="field row">
        <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class:"col-xs-12" %>
      </div>
      <div class="actions row">
          <%= f.submit 'Update Book', class:"btn btn-primary col-xs-12" %>
      </div>
    <% end %>

    <%= link_to "Show", book_path(@book) %>
    <span>|</span>
    <%= link_to "Back", books_path %>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/books/index.html.erb
<div class="row">

<% if @book.errors.any? %>
   <%= @book.errors.count %>errors prohibited this user from being saved:
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
   <% end %>
    </ul>
  </div>
<% end %>

<div class="col-xs-3">
  <!-- ユーザー情報 -->
  <%= render 'books/user', user: @user %>
  <!-- 新規投稿 -->
  <%= render 'books/book', book: @book %>
</div>

<!--投稿一覧-->
<div class="col-xs-9">
  <h2>Books</h2>
    <table class="table table-hover table-inverse">
     <thead>
     	<tr>
     	  <th></th>
     	  <th>Title</th>
     	  <th>Opinion</th>
        <th colspan="3"></th>
        <!-- th colspan はセルの連結 -->
     	</tr>
     </thead>
     <tbody>
      <% @books.each do |book| %>
    	<tr>
    	  <td><%= link_to (attachment_image_tag book.user, :profile_image, :fill, 40, 40, format:'jpeg', fallback:"no_image.jpg", size:'40x40'), user_path(book.user), class:"attachment user profile_image" %></td>
        <!-- 画像からリンクに飛ぶためには上のように記述する！ -->
      	  <td><%= link_to book.title, book_path(book) %></td>
          <td><%= book.body %></td>
          <td>
          <% if book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(book), method: :delete do %>
                <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                <%= book.favorites.count %>
                <% end %>
            <% else %>
                <%= link_to book_favorites_path(book), method: :post do %>
                <i class="fa fa-heart-o" aria-hidden="true"></i>
                <%= book.favorites.count %>
                <% end %>
          <% end %>
          </td>
          <td>コメント数：<%= book.book_comments.count %></td>
        </tr>
      <% end %>
     </tbody>
     </thead>
    </table>
</div>
</div>

app/views/books/show.html.erb
<div class="row">

<p id="notice">
  <%=  notice %>
</p>

<div class="col-xs-3">
  <!-- ユーザー情報 -->
  <%= render 'books/user', user: @user %>
  <!-- 新規投稿 -->
  <%= render 'books/book', book: @book %>
</div>

<!-- 本の詳細 -->
<div class="col-xs-9">
<h2>Book detail</h2>

  <table class="table">
  <tbody>
      <tr>
        <td><%= attachment_image_tag @user, :profile_image,:fill, 40, 40, class:"attachment user profile_image", fallback:"no_image.jpg" %><br><%= link_to @user.name, user_path(@user) %></td>
        <td><%= link_to @book2.title, book_path(@book2)  %></td>
        <td><%= @book2.body %></td>

        <td>
        <% if @book2.favorited_by?(current_user) %>
              <%= link_to book_favorites_path(@book2), method: :delete do %>
              <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
              <%= @book2.favorites.count %>
              <% end %>
          <% else %>
              <%= link_to book_favorites_path(@book2), method: :post do %>
              <i class="fa fa-heart-o" aria-hidden="true"></i>
              <%= @book2.favorites.count %>
              <% end %>
        <% end %>
        </td>

        <td>コメント数：<%= @book2.book_comments.count %></td>

        <td>
          <% @book2.book_comments.each do |book_comment| %>
             <%= book_comment.comment %><br>

             <% if book_comment.user_id == current_user.id %>
                 <%= link_to "Destroy", book_book_comments_path(book_comment.book.id, book_comment.id), method: :delete, "data-confirm" => "本当に削除しますか？", class:"btn-sm btn-danger" %>
             <% end %>
             <br>
          <% end %>
        </td>

        

        <% if @user == current_user %>
        <td><%= link_to "Edit", edit_book_path(@book2), class:"btn-sm btn-success" %></td>
        <td><%= link_to "Destroy", destroy_book_path(@book2), method: :delete, "data-confirm" => "本当に削除しますか？", class:"btn-sm btn-danger" %></td>
        <% end %>

      </tr>

  </tbody>
  </table>

  <p id="notice">
    <%=  notice %>
  </p>

　<% if @book2.errors.any? %>
     <%= @book2.errors.count %>errors prohibited this user from being saved:
    <div id="error_explanation" class="alert alert-danger">
      <ul>
        <% @book2.errors.full_messages.each do |message| %>
          <li><%= message %></li>
     <% end %>
      </ul>
    </div>
  <% end %>
  

  <%= form_for [@book2, @book_comment] do |f| %>
    <div class="field row">
     <%= f.text_area :comment, rows:'5', class: "form-control" %>
    </div>
    <div class="actions row">
     <%= f.submit "Create Comment", class: "btn btn-primary col-xs-12" %>
    </div>
  <% end %>
  </div>
</div>

app/views/homes/about.html.erb
<h1>Welcome to<span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>

app/views/homes/new.html.erb
<div class="row">

<p id="notice">
  <%=  notice %>
</p>

  <div class="top-message col-md-offset-3 col-md-6">
	<h1>welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>
	<p>In<span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
	<p>you can share and exchange  your opinions , inpressions , and emotions</p>
	<p> about various books!</p>
  </div>
	<div class="btn-wrapper">
	      <div class="row">
	         <p><%= link_to "Log in", new_user_session_path, class:"btn btn-info col-xs-6 col-xs-offset-3 sign_in" %></p>
	      </div>
	      <div class="row">
	        <p><%= link_to "Sign up", new_user_registration_path, class:"btn btn-success col-xs-6 col-xs-offset-3 sign_up" %></p>
	      </div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2.work</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/5cb11f9174.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class="nav navbar-nav navbar-left">
      <span>Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to " Home", user_path(current_user.id), class:"glyphicon glyphicon-home home" %>
          <!--    もってくるときは関数名で-->
          </li>
          <li>
            <%= link_to " Users", users_path, class:"glyphicon glyphicon-user users" %>
          </li>
          <li>
            <%= link_to " Books", books_path, class:"glyphicon glyphicon-book books" %>
          </li>
          <li>
            <%= link_to " logout", destroy_user_session_path, method: :delete, class:"glyphicon glyphicon-log-out logout"%>
          </li>
        <% else %>
          <li>
            <%= link_to " Home", root_path, class:"glyphicon glyphicon-home home" %>
          </li>
          <li>
            <%= link_to " About", home_about_path, class:"glyphicon glyphicon-link about" %>
          </li>
          <li>
            <%= link_to " sign up", new_user_registration_path, class:"glyphicon glyphicon-edit sign_up" %>
          </li>
          <li>
            <%= link_to " login",  new_user_session_path, class:"glyphicon glyphicon-log-in sign_in" %>
          </li>
        <% end %>
      </ul>
    </nav>
    </div>
    </header>
    <div class="body">
      <div class="container">
<!--         diviseで実装されているサクセスメッセージなどが表示される -->
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>

        <%= yield %>

       </div>
    </div>

    <footer>
     <div class="container">
      <div class="row">
       <div class="col-xs-3 col-xs-offset-9">
        <p>CopyRight Infratop.inc</p>
       </div>
      </div>
     </div>
    </footer>
  </body>
</html>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% end %>
<% end %>

app/views/users/_book.html.erb
<!-- 新規投稿 -->
<h2>New book</h2>
 <%= form_for(book) do |f| %>
  <div class="field row">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class:"col-xs-12 book_title" %>
  </div>
  <div class="field row">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class:"col-xs-12 book_body" %>
  </div>
  <div class="actions row">
    <%= f.submit 'Create Book', class:"btn btn-primary col-xs-12" %>
  </div>
 <% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
 <% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
   <!-- フォローを外す -->
	<%= render 'unfollow', user: @user %>
  <% else %>
    <!-- フォローをする -->
	<%= render 'follow', user: @user %>
  <% end %>
  </div>
<% end %>  

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large follow-btn" %>
<% end %>

app/views/users/_user.html.erb
<!-- ユーザー情報　-->
 <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 60, 60, class:"attachment user profile_image", fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
        <tr>
        </tr>
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>
        <tr>
          <th>follows</th>
          <th><%= link_to user.followings.count, following_user_path(user) %></th>
        </tr>
        <tr>
          <th>followers</th>
          <th><%= link_to user.followers.count, followers_user_path(user) %></th>
        </tr>
        <tr>
          <th>
             <%= render 'follow_form', user: @user %>
          </th>
          <th></th>
        </tr>
    </tbody>
  </table>

<div class="row">
<% if user == current_user %>
  <p><%= link_to "", edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
<% else %>
  <p><%= link_to "", user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
<% end %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

   <% if @user.errors.any? %>
   <%= @user.errors.count %>errors prohibited this user from being saved:
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

    <div class="field">
      <label for="user_name">Name</label>
        <%= f.text_field :name, class:"edit_user" %>
    </div>
        <!-- <span class="fa fa-user form-control-icon" aria-hidden="true"></span> -->
    <div class="field">
        <label for="user_image">Image</label>
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format:'jpeg' %>
        <%= f.attachment_field :profile_image, class:"user_image" %>
    </div>
    <div class="field">
        <label for="user_introduction">Introduction</label>
        <%= f.text_area :introduction, class:"introduction" %>
    </div>
    <div class="actions">
        <%= f.submit "Update User", class:"update" %>
    </div>
<% end %>

app/views/users/index.html.erb
<div class="row">

<div class="col-xs-3">
<!-- ユーザー情報　-->
  <%= render 'users/user', user: @user %>
<!-- 新規投稿部分　-->
  <%= render 'users/book', book: @book %>
</div>

<!--ユーザー一覧-->
<div class="col-xs-9">
  <h2>Users</h2>
    <table class="table">
     <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
     </thead>
     <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format:'jpeg', class: "attachment user profile_image", fallback: "no_image.jpg", size:'40x40' %></td>
          <td><%= user.name %></td>
          <td>フォロー数：<%= user.followings.count %></td>
          <td>フォロワー数：<%= user.followers.count %></td>
          <!-- renderは＠を使わないとできない -->
          <td>
             <% unless current_user?(user) %>
              <div id="follow_form">
              <% if current_user.following?(user) %>
               <!-- フォローを外す -->
              <%= render 'unfollow', user: user %>
              <% else %>
                <!-- フォローをする -->
              <%= render 'follow', user: user %>
              <% end %>
              </div>
            <% end %>  
          </td>
          <td><%= link_to 'Show', user_path(user) %></td>
        </tr>
      <% end %>
      </tbody>
      </thead>
    </table>

</div>
</div>

app/views/users/show.html.erb
<div class="row">

<p id="notice">
  <%=  notice %>
</p>

<div class="col-xs-3">
<!-- ユーザー情報　-->
  <%= render 'users/user', user: @user %>
<!-- 新規投稿部分　-->
  <%= render 'users/book', book: @book %>
</div>
<!-- 自分が投稿した本の一覧部分　-->
  <div class="col-xs-9">
  <h2>Books</h2>

    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
      	<% @books.each do |book| %>
          <tr>
            <td><%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format:'jpeg', class:"attachment user profile_image", fallback: "no_image.jpg", size:'40x40' %></td>
            <!-- 画像からプロフィール詳細にとべるように後で設定する -->
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
            <td>コメント数：<%= book.book_comments.count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>

app/views/users/show_follow.html.erb
<div class="row">
  <h2>Follow Users</h2>
    <table class="table">
     <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
     </thead>
     <tbody>
		<% @user.followings.each do |user| %>
		<tr>
		  <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format:'jpeg', class: "attachment user profile_image", fallback: "no_image.jpg", size:'40x40' %></td>
		  <td><%= user.name %></td>
          <td>フォロー数：<%= user.followings.count %></td>
          <td>フォロワー数：<%= user.followers.count %></td>
          <td><%= render 'follow_form' %></td>
		  <td><%= link_to 'Show', user_path(user) %></td>
		</tr>

		<% end %>
	 </tbody>
	</table>
	
</div>

app/views/users/show_follower.html.erb
<div class="row">
  <h2>Follower Users</h2>
    <table class="table">
     <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
     </thead>
     <tbody>
		<% @user.followers.each do |user| %>
		<tr>
		  <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format:'jpeg', class: "attachment user profile_image", fallback: "no_image.jpg", size:'40x40' %></td>
		  <td><%= user.name %></td>
		  <td>フォロー数：<%= user.followings.count %></td>
          <td>フォロワー数：<%= user.followers.count %></td>
          <td><%= render 'follow_form' %></td>
		  <td><%= link_to 'Show', user_path(user) %></td>
		</tr>
	<% end %>
	</tbody>
	</table>
</div>